version: '3.8'
services:
    php-apache-environment:
        container_name: my-php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mydb
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    mydb:
        container_name: mydb
        image: anujarcanetinmen/mymysql:V1.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: 'MYSQL_USER'
            MYSQL_PASSWORD: MYSQL_PASSWORD

        ports:
            - "9906:3306"
        volumes:
          - ./dbdata:/var/lib/mysql

    phpmyadmin:
        image: anujarcanetinmen/myphpmyadmin:V1.0
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
